package org.hy.microservice.cdc.dataSource;

import java.util.List;
                
import org.hy.common.xml.XJava;
import org.hy.microservice.timing.dataSource.DataSourceConfig;
import org.hy.microservice.timing.dataSource.IDataSourceConfigService;





rule "XRule_Timing_DataSourceConfig_Decrypt_DSConfig"
    dialect "java"
    when
        v_DSConfig : DataSourceConfig();
    then
        if ( v_DSConfig.getUserName() != null && v_DSConfig.getUserName().indexOf("encrypt:") >= 0 )
         {
            v_DSConfig.setUserName(((IDataSourceConfigService)XJava.getObject("DataSourceConfigService")).decryptUserName(v_DSConfig));
         }
         
         if ( v_DSConfig.getPassword() != null && v_DSConfig.getPassword().indexOf("encrypt:") >= 0 )
         {
            v_DSConfig.setPassword(((IDataSourceConfigService)XJava.getObject("DataSourceConfigService")).decryptPassword(v_DSConfig));
         }
end;





rule "XRule_Timing_DataSourceConfig_Decrypt_List"
    dialect "java"
    when
        $list : List()
    then
        for(int x = 0; x < $list.size(); x++)
        {
            DataSourceConfig v_DSConfig = (DataSourceConfig) $list.get(x);
        
             if ( v_DSConfig.getUserName() != null && v_DSConfig.getUserName().indexOf("encrypt:") >= 0 )
             {
                v_DSConfig.setUserName(((IDataSourceConfigService)XJava.getObject("DataSourceConfigService")).decryptUserName(v_DSConfig));
             }
             
             if ( v_DSConfig.getPassword() != null && v_DSConfig.getPassword().indexOf("encrypt:") >= 0 )
             {
                v_DSConfig.setPassword(((IDataSourceConfigService)XJava.getObject("DataSourceConfigService")).decryptPassword(v_DSConfig));
             }
        }
end;
